name: impresiones digitales
favicon: null
layout_spectrum: 0.25301
typography_spectrum: 0.74355
title: impresiones digitales
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#081320'
    - '#c5c5c3'
    - '#727e95'
    - '#243a32'
    - '#edeef0'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
